
/* =======================================================================
 *  Copyright (C) GMVIS Skysoft S.A., 2019
 * ======================================================================= */

/**
 * @file
 * @brief Partition (Id: 0, Name: p0) Initialization
 * @note Generated by XKY Configurator Tool v4.0a
 */

#include <bare.h>

/**
 * @brief Partition entry point
 */
extern int entry_point() __attribute__ ((weak));

/**
 * @brief Program entry point
 */
int bare_main(void) {

    /* call entry point */
    if (entry_point != NULL) {
        entry_point();
    }

    return 0;
}
